usr/lib/qt4/plugins/styles/libskulpture.so
usr/share/kde4/apps/color-schemes/SkulptureChocolate.colors
usr/share/kde4/apps/color-schemes/SkulptureIce.colors
usr/share/kde4/apps/color-schemes/SkulptureMint.colors
usr/share/kde4/apps/color-schemes/SkulptureStone.colors
usr/share/kde4/apps/color-schemes/SkulptureStrawberry.colors
usr/share/kde4/apps/color-schemes/SkulptureVanilla.colors
usr/share/kde4/apps/kstyle/themes/skulpture.themerc
